#!/usr/bin/env python3
"""stdlib mcp server fronting the real, self hosted openproject instance
for spear-shield-agents. same shape as the reference's
mcp-servers/calculator/server.py (stdlib http server, no pip deps), but
this one calls a real backend rather than doing local arithmetic.

two real tools: search_work_packages (read) and update_work_package
(write), matching PHASE2_PLAN.md section 4's naming, both mapped onto
openproject's own rest api v3, called over the cluster network directly
against openproject's internal-http:8080 port, using each caller's own
real personal openproject api token, not a shared service credential.

identity: the mcp broker hairpins the caller's original bearer token on
every tools/call (confirmed in the reference's own
manifests/20-security/03-auth-policies.yaml comment, and re-checked by
authorino on this same internal hop, not skipped). this server reads
that Authorization header and decodes the jwt payload to get
preferred_username, no signature check here since authorino already did
that before this server ever sees the request, this is authorization
logic on top, not primary authentication.

primary defenses, PHASE2_PLAN.md section 5: assignee=self checked before
any write reaches openproject (a caller can only move their own assigned
work package, never someone else's, even though tool level rbac already
gates who may call update_work_package at all).

the nightmare 3 tool response check used to live here too, moved out to
spear-shield-mcp-guard-proxy instead (see that server's own module
docstring), this server has no guardrails code of its own now, proving
the proxy alone is enough, not a redundant second check on top of it.
"""

from __future__ import annotations

import base64
import hmac
import json
import os
import urllib.error
import urllib.parse
import urllib.request
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any
from urllib.parse import urlparse

HOST = os.environ.get("MCP_HOST", "0.0.0.0")
PORT = int(os.environ.get("MCP_PORT", "8000"))
PROTOCOL = os.environ.get("MCP_PROTOCOL_VERSION", "2025-03-26")

# closes the same direct-bypass gap calculator-mcp closes, see that
# server.py's own comment, identical mechanism, this server's own
# httproute stamps this on every tools/call envoy's ext_proc hairpins here.
BACKEND_SECRET = os.environ.get("MCP_BACKEND_SECRET", "")

# openproject's own internal clusterip service, not its external route.
# the personal api token is the only auth layer here, openproject's
# native login already gates the external route for human users.
OPENPROJECT_INTERNAL_URL = os.environ.get(
    "OPENPROJECT_INTERNAL_URL", "http://spear-openproject.spear-shield-agents.svc.cluster.local:8080"
)
# rails' own host authorization and force_ssl checks reject a plain
# internal http call otherwise, found live in section 4's build: send
# the external hostname as Host and claim https via X-Forwarded-Proto
# so rails treats the request as if it arrived through its own external
# route, even though it took the internal path.
# no hardcoded fallback on purpose, this has to exactly match
# openproject's own OPENPROJECT_HOST__NAME on this cluster or rails'
# host authorization check rejects the request, section 4's own found
# live note, a stale default here would silently 400 on a different
# cluster rather than fail fast
OPENPROJECT_HOST_HEADER = os.environ["OPENPROJECT_HOST_HEADER"]
OPENPROJECT_PROJECT = os.environ.get("OPENPROJECT_PROJECT_IDENTIFIER", "data-governance")
# one file per persona, secret spear-openproject-api-tokens mounted here,
# key becomes filename, value is that persona's own real openproject
# personal access token, generated by themselves, section 4
OPENPROJECT_TOKENS_DIR = os.environ.get("OPENPROJECT_TOKENS_DIR", "/var/run/secrets/openproject-tokens")

# openproject has no literal "approved" status by default, checked live
# against this instance's real /api/v3/statuses. these are the aliases
# this server accepts on update_work_package, mapped to this instance's
# real status ids, confirmed live during section 4's build (siddhartha.de's
# own real token moved work package 39 from "on hold" to "in progress"
# this exact way, this is that same real transition, now reachable
# through the tool rather than a one off curl)
STATUS_ALIASES = {
    "approved": 7,       # in progress, the escalation request now proceeds
    "in_progress": 7,
    "in progress": 7,
    "new": 1,
    "open": 1,
    "on_hold": 13,
    "on hold": 13,
    "closed": 12,
    "done": 12,
    "rejected": 14,
    "denied": 14,
}


def _b64url_decode(segment: str) -> bytes:
    padded = segment + "=" * (-len(segment) % 4)
    return base64.urlsafe_b64decode(padded)


def caller_username(auth_header: str) -> str | None:
    """pulls preferred_username out of the caller's bearer token payload.

    no signature verification here on purpose, authorino already
    validated this same token on the mcps listener's authpolicy before
    this request ever reached this pod, see PHASE2_PLAN.md section 4.
    """
    if not auth_header.lower().startswith("bearer "):
        return None
    token = auth_header.split(" ", 1)[1].strip()
    parts = token.split(".")
    if len(parts) != 3:
        return None
    try:
        payload = json.loads(_b64url_decode(parts[1]))
    except (ValueError, UnicodeDecodeError):
        return None
    return payload.get("preferred_username")


def persona_token(username: str) -> str | None:
    path = os.path.join(OPENPROJECT_TOKENS_DIR, username)
    try:
        with open(path, encoding="utf-8") as f:
            return f.read().strip()
    except FileNotFoundError:
        return None


def openproject_request(method: str, path: str, token: str, body: dict[str, Any] | None = None) -> dict[str, Any]:
    url = f"{OPENPROJECT_INTERNAL_URL}{path}"
    data = json.dumps(body).encode("utf-8") if body is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    basic = base64.b64encode(f"apikey:{token}".encode("utf-8")).decode("ascii")
    req.add_header("Authorization", f"Basic {basic}")
    req.add_header("Host", OPENPROJECT_HOST_HEADER)
    req.add_header("X-Forwarded-Proto", "https")
    req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            return json.loads(resp.read().decode("utf-8") or "{}")
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"openproject {method} {path} -> {exc.code}: {detail}") from exc


def tool_defs() -> list[dict[str, Any]]:
    return [
        {
            "name": "search_work_packages",
            "description": "search real work packages in the data governance openproject project, scoped to the caller's own assignments",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "status": {"type": "string", "description": "optional status name filter, e.g. open, on hold, closed"},
                },
            },
        },
        {
            "name": "update_work_package",
            "description": "update a work package's status, only the caller's own assigned work packages",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "id": {"type": "integer", "description": "real openproject work package id"},
                    "status": {"type": "string", "description": "target status, e.g. approved, closed, rejected"},
                },
                "required": ["id", "status"],
            },
        },
    ]


def run_search_work_packages(username: str, token: str, arguments: dict[str, Any]) -> str:
    me = openproject_request("GET", "/api/v3/users/me", token)
    user_id = me["id"]
    filters = [{"assignee": {"operator": "=", "values": [str(user_id)]}}]
    status = arguments.get("status")
    if status:
        alias_id = STATUS_ALIASES.get(status.strip().lower())
        if alias_id:
            filters.append({"status": {"operator": "=", "values": [str(alias_id)]}})
    query = urllib.parse.urlencode({"filters": json.dumps(filters)})
    path = f"/api/v3/projects/{OPENPROJECT_PROJECT}/work_packages?{query}"
    result = openproject_request("GET", path, token)
    elements = result.get("_embedded", {}).get("elements", [])
    rows = [
        {
            "id": el["id"],
            "subject": el["subject"],
            "status": el.get("_links", {}).get("status", {}).get("title"),
            "assignee": el.get("_links", {}).get("assignee", {}).get("title"),
        }
        for el in elements
    ]
    return json.dumps({"caller": username, "count": len(rows), "work_packages": rows})


def run_update_work_package(username: str, token: str, arguments: dict[str, Any]) -> str:
    wp_id = int(arguments["id"])
    status_name = str(arguments["status"]).strip().lower()
    status_id = STATUS_ALIASES.get(status_name)
    if status_id is None:
        raise ValueError(f"unknown status '{arguments['status']}', known aliases: {sorted(STATUS_ALIASES)}")

    current = openproject_request("GET", f"/api/v3/work_packages/{wp_id}", token)
    me = openproject_request("GET", "/api/v3/users/me", token)
    assignee_href = current.get("_links", {}).get("assignee", {}).get("href") or ""
    # primary defense, PHASE2_PLAN.md section 5: assignee=self, checked
    # here before the request reaches openproject's own write path, not
    # relying solely on tool level rbac at the gateway
    if assignee_href != f"/api/v3/users/{me['id']}":
        raise PermissionError(
            f"work package {wp_id} is not assigned to {username}, refusing to update someone else's work package"
        )

    lock_version = current["lockVersion"]
    body = {"lockVersion": lock_version, "_links": {"status": {"href": f"/api/v3/statuses/{status_id}"}}}
    updated = openproject_request("PATCH", f"/api/v3/work_packages/{wp_id}", token, body)
    return json.dumps(
        {
            "caller": username,
            "id": updated["id"],
            "subject": updated["subject"],
            "status": updated.get("_links", {}).get("status", {}).get("title"),
        }
    )


def run_tool(name: str, arguments: dict[str, Any], username: str) -> str:
    token = persona_token(username)
    if not token:
        raise ValueError(f"no openproject personal access token on file for '{username}'")
    if name == "search_work_packages":
        return run_search_work_packages(username, token, arguments)
    if name == "update_work_package":
        return run_update_work_package(username, token, arguments)
    raise ValueError(f"unknown tool: {name}")


def handle_rpc(body: dict[str, Any], auth_header: str) -> dict[str, Any] | None:
    method = body.get("method")
    request_id = body.get("id")
    params = body.get("params") or {}

    if method == "notifications/initialized":
        return None

    if method in ("initialize", "mcp/initialize"):
        client_version = params.get("protocolVersion") or PROTOCOL
        return {
            "jsonrpc": "2.0",
            "id": request_id,
            "result": {
                "protocolVersion": client_version,
                "capabilities": {"tools": {"listChanged": False}},
                "serverInfo": {"name": "spear-openproject-mcp", "version": "0.1.0"},
            },
        }

    if method in ("ping", "mcp/ping"):
        return {"jsonrpc": "2.0", "id": request_id, "result": {}}

    if method == "tools/list":
        return {"jsonrpc": "2.0", "id": request_id, "result": {"tools": tool_defs()}}

    if method == "tools/call":
        username = caller_username(auth_header)
        if not username:
            return {
                "jsonrpc": "2.0",
                "id": request_id,
                "error": {"code": -32001, "message": "no caller identity on this request"},
            }
        name = params.get("name")
        arguments = params.get("arguments") or {}
        text = run_tool(name, arguments, username)

        return {
            "jsonrpc": "2.0",
            "id": request_id,
            "result": {
                "content": [{"type": "text", "text": text}],
                "isError": False,
            },
        }

    return {
        "jsonrpc": "2.0",
        "id": request_id,
        "error": {"code": -32601, "message": f"unsupported method: {method}"},
    }


class Handler(BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"

    def log_message(self, fmt: str, *args: Any) -> None:
        print(f"mcp {self.address_string()} {fmt % args}")

    def _send(self, code: int, payload: bytes, content_type: str) -> None:
        self.send_response(code)
        self.send_header("content-type", content_type)
        self.send_header("content-length", str(len(payload)))
        self.send_header("cache-control", "no-store")
        self.end_headers()
        if payload:
            self.wfile.write(payload)

    def do_GET(self) -> None:  # noqa: N802
        path = urlparse(self.path).path
        if path in ("/health", "/healthz", "/ready"):
            self._send(200, b'{"status":"ok"}', "application/json")
            return
        self._send(404, b'{"error":"not found"}', "application/json")

    def do_POST(self) -> None:  # noqa: N802
        path = urlparse(self.path).path
        if path not in ("/", "/mcp", "/mcp/"):
            self._send(404, b'{"error":"not found"}', "application/json")
            return
        length = int(self.headers.get("content-length", "0"))
        raw = self.rfile.read(length) if length else b"{}"
        try:
            body = json.loads(raw.decode("utf-8") or "{}")
        except json.JSONDecodeError:
            self._send(400, b'{"error":"invalid json"}', "application/json")
            return

        if BACKEND_SECRET and body.get("method") == "tools/call":
            supplied = self.headers.get("x-spear-shield-backend-secret", "")
            if not hmac.compare_digest(supplied, BACKEND_SECRET):
                self._send(
                    401,
                    b'{"error":"direct access to this mcp server is not permitted, go through the gateway"}',
                    "application/json",
                )
                return

        auth_header = self.headers.get("authorization", "")
        try:
            result = handle_rpc(body, auth_header)
        except Exception as exc:  # noqa: BLE001
            result = {
                "jsonrpc": "2.0",
                "id": body.get("id"),
                "error": {"code": -32000, "message": str(exc)},
            }

        if result is None:
            self._send(204, b"", "application/json")
            return

        encoded = json.dumps(result).encode("utf-8")
        accept = (self.headers.get("accept") or "").lower()
        if "text/event-stream" in accept:
            sse = b"event: message\ndata: " + encoded + b"\n\n"
            self._send(200, sse, "text/event-stream")
            return
        self._send(200, encoded, "application/json")


def main() -> None:
    server = ThreadingHTTPServer((HOST, PORT), Handler)
    print(f"spear-openproject-mcp listening on {HOST}:{PORT}")
    server.serve_forever()


if __name__ == "__main__":
    main()
