apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1","kind":"DestinationRule","metadata":{"annotations":{},"name":"spear-shield-nemo-guard","namespace":"spear-shield-agents"},"spec":{"host":"spear-shield-nemo-guard.spear-shield-agents.svc.cluster.local","trafficPolicy":{"tls":{"insecureSkipVerify":true,"mode":"SIMPLE"}}}}
  creationTimestamp: "2026-10-02T07:05:23Z"
  generation: 1
  name: spear-shield-nemo-guard
  namespace: spear-shield-agents
  resourceVersion: "6617075"
  uid: fc4b933e-1b5c-4b73-bc14-dd4f2e64f0b0
spec:
  host: spear-shield-nemo-guard.spear-shield-agents.svc.cluster.local
  trafficPolicy:
    tls:
      insecureSkipVerify: true
      mode: SIMPLE
